// Run this script once before your first call to main.js to insert initial data into db
// If you were to go into your mongosh and read your dbs, "communitySiteDB" should be listed

const { MongoClient, ObjectId } = require('mongodb');
const mongoUrl = "mongodb://127.0.0.1:27017/";
const client = new MongoClient(mongoUrl);
const crypto = require('crypto');

// hashing using the same exact hashing method as the account creation
function hashed(password) {
    return crypto.createHash('sha256').update(password).digest('hex');
}

// Inserts dummy data into the database
async function insertDocuments() {
    try {
        await client.connect();
        console.log("\nConnected to mongodb...\n");
        const db = client.db("communitySiteDB");

        // Resets, clears existing data if you were to call insertion again
        await db.collection("userCollection").deleteMany({});
        await db.collection("communityCollection").deleteMany({});
        await db.collection("postCollection").deleteMany({});
        console.log("reset collections");


        // --- Insert test users
        // added email field missing on collection diagram
        const testUsers = [
            { name: "Jacob", email: "jacob@gmail.com", password: hashed("12345") },
            { name: "Kayvon", email: "kayvon@gmail.com", password: hashed("12345") },
            { name: "Mitch", email: "mitch@gmail.com", password: hashed("12345") },
            { name: "dev", email: "dev@gmail.com", password: hashed("12345") }
        ];
        await db.collection("userCollection").insertMany(testUsers);
        console.log(" * inserted test users");


        // --- Insert test invitations
        // pretty sure _id is auto generated on doc insertion but made it clear
        // to reflect collections diagram
        const commID1 = new ObjectId;
        const commID2 = new ObjectId;
        const testCommunities = [
            { _id: commID1, name: "CompSci", description: "Computer Science Community"},
            { _id: commID2, name: "Baking", description: "Baking Community"}
        ];
        await db.collection("communityCollection").insertMany(testCommunities);
        console.log(" * inserted test communities");


        // --- Insert test posts
        // Each collection doc has its own _id, autogenerated if not specified,
        // so if the 'id' in our diagram is pointing to the id of the community the
        // post belongs to, I think it must be a separate field
        // So there is _id which is the ObjectId and then I made a communityID
        const postID1 = new ObjectId();
        const postID2 = new ObjectId();
        const testPosts = [
            { _id: postID1, communityID: commID1, user: "anonymous user 1", text: "Hi this is my post", replies: []},
            { _id: postID2, communityID: commID2, user: "anonymous user 2", text: "Dead community...", replies: []}
        ];
        await db.collection("postCollection").insertMany(testPosts);
        console.log(" * inserted test posts");

        console.log("\nDatabase docs successfully inserted.\n");

    } catch (err) {
        console.error("Error inserting test docs to database:", err);
    } finally {
        await client.close();
    }
}

insertDocuments();